language: python
sudo: false
dist: trusty
python: "2.7"
install:
  - pip install -U pip
  - make deps
  - curl -k -LO https://releases.hashicorp.com/consul/0.6.4/consul_0.6.4_linux_amd64.zip
  - unzip consul_0.6.4_linux_amd64.zip
  - export GOMAXPROCS=8 PATH=$PATH:$PWD
  - sed -i 's/bind 127.0.0.1 ::1/bind 127.0.0.1/g' /etc/redis/redis.conf && service redis-server restart
  - make start-consul
script:
  - make ci-test
  - make stop-consul
services:
  - mongodb
  - redis
notifications:
  email:
    recipients:
      - tsuru@corp.globo.com
    on_success: change
    on_failure: change
addons:
  apt:
    packages:
    - redis-server
