name: ci
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-18.04
    services:
      mongodb:
        image: mongo:4
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 2.7
        uses: actions/setup-python@v2
        with:
          python-version: 2.7
      - uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: '4.x'
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo -E apt-get install -y unzip
          pip install -U pip
          make deps
          curl -k -LO https://releases.hashicorp.com/consul/0.6.4/consul_0.6.4_linux_amd64.zip
          unzip consul_0.6.4_linux_amd64.zip
          export GOMAXPROCS=8 PATH=$PATH:$PWD
          make start-consul
      - name: Run test
        run: make ci-test
